### ISSUE TITLE
"You must submit files" does not disappear

### ISSUE THREAD

**Issue by smimram** [strub/handin#11]
When we upload the wrong files, we get a message "You must submit files...". If after that we submit again with the right files, the messages does not disappear, which is confusing.

**Comment by strub** [comment]
This is not an error message but an information that is always present. I could rephrase it.

(I still have to push the error message on submission)

**Comment by strub** [comment]
Fixed.

**Comment by smimram** [comment]
Could you please at least make them less visible? (grayish instead of yellowish) They look like errors.
